### ISSUE TITLE
IntelliJ Idea: Unresolved reference: serializer

### ISSUE THREAD

**Issue by dmexe** [Kotlin/kotlinx.serialization#257]
Idea doesn't compile project files with an error: "Kotlin: Unresolved reference: serializer". 
I tried various cleanup task and IDE restarting and a project reimport but it doesn't solve the issue.

Meantime gradle itself works perfectly without any errors.

build.gradle.kts
```
buildscript {
  repositories { jcenter() }

  dependencies {
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0")
    classpath("org.jetbrains.kotlin:kotlin-serialization:1.3.0")
  }
}

apply {
  plugin("kotlin")
  plugin("kotlinx-serialization")
  ...
}

dependencies {
  compile(kotlin("stdlib", "1.3.0"))
  compile("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.0")
  ...
}
```

Idea version
```
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
```

Idea kotlin plugin version:
```
1.3.0-release-IJ2018.2-1
```

**Comment by sandwwraith** [comment]
Hi, is it error on a highlighting level (`.serializer()` code is shown as red) or only compile error? If latter, delegate build in IDEA to Gradle (Settings - Build, Execution, Deployment - Build Tools - Gradle - Runner - tick Delegate IDE build/run actions to gradle).

**Comment by dmexe** [comment]
It was a compilation error:
```
/Users/dima/apps/teamcity-sync/src/main/kotlin/me/dmexe/teamcity/sync/github/GithubQuery.kt
Error:(16, 38) Kotlin: Unresolved reference: serializer

16: JSON.stringify(ReposQuery.serializer(), query)
```

 After I turned on "delegate build to gradle" a project compiles without errors. In 1.3 release notes "Serialization support should work out of the box, if you have 1.3 Kotlin plugin installed" is it still not true?

**Comment by sandwwraith** [comment]
And the next sentence after the one you cited is about delegation to gradle. "Serialization support" was mainly for highlighting generated code. The issue with compilation is known and likely will be fixed in the next release.

**Comment by jguerinet** [comment]
@sandwwraith is there an issue (on GitHub or YouTrack) to keep track of when this compilation issue will be fixed? I can't seem to find it, but I may be using the wrong keywords in my search.

**Comment by sandwwraith** [comment]
@jguerinet I think you can track this one: https://github.com/Kotlin/kotlinx.serialization/issues/265

**Comment by tromper** [comment]
@sandwwraith I'm having a similar issue with Unresolved reference: serializer being shown in red in IDEA.  I've updated to latest versions (e.g. have the Kotlin 1.3 plugin installed and latest IDEA), maven compiles ok, I see the generated code, can run it fine, but can't get rid of the red highlighting.

**Comment by grahamcummins-wf** [comment]
I have the same issue as @tromper. 
My project builds and works as expected using a maven build. With the build delegated to maven, serialization tests also build, run, and pass from IntelliJ. All references to the ".serializer()" method on any @Serializable class show up as an error in IntelliJ's linter (red highlight. File defining them has a red underscore).
It's not a show stopper, since the build works, but it's annoying, particularly when a new developer starts on the project (s/he always spends a few hours trying to fix the "Unresolved reference", no matter how much we try to document the linter failure) .

**Comment by sandwwraith** [comment]
Hm, probably this is a particular Maven import issue, since Gradle projects with serialization are imported into IDE correctly. I'll check this out.

**Comment by grahamcummins-wf** [comment]
That sounds right. I haven't seen this on my personal projects (which are gradle projects). Only on this one at work (where we use maven)

**Comment by sandwwraith** [comment]
@grahamcummins-wf Indeed, you can track #307

**Comment by IARI** [comment]
@sandwwraith I have the same Issue, but with a gradle project. I haven't been able to get rid of the synta highlighting.

**Comment by sandwwraith** [comment]
@IARI Have you tried reimporting project/deleting `.idea` folder? Is Kotlin plugin in IDEA higher than 1.3? Does Gradle build passes correctly?

**Comment by IARI** [comment]
@sandwwraith 
Kotlin and IDEA plugin ist 1.3.11, Gradle build passes correctly.
I was able to get rid of it temporarily, I think by reimporting the project. but I'll have to try that again to be sure.

**Comment by TorRanfelt** [comment]
@sandwwraith For me the problem is fixed by deleting the .idea folder, but I have to do it often.

**Comment by IARI** [comment]
yep it is fixxed temporarily for me by reimporting the gradle project. but that only lasts until i think idea is restarted oder something else changes

**Comment by chrisjenx** [comment]
Same here, project compiles, but Intellij can't resolve the `serializer()` extension.

**Comment by rsCtrl** [comment]
Same.  Updating gradle dependencies fixes the issue until i restart the idea.

**Comment by coder82** [comment]
Same here, IDEA highlights it in red but all runs.
[screenshot](https://i.imgur.com/RS3ph1c.png)

**Comment by fracturizer** [comment]
Have same highlighting issue of serializable() in Android Studio. Does not go away even after "Invalidate Caches & Restart"

**Comment by sandwwraith** [comment]
@fracturizer @coder82 Can you please write versions of your IDEs?

**Comment by danielebartorilla** [comment]
Same here with a multi module android project

Android studio 3.3.2

**Comment by fracturizer** [comment]
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

BTW. Highlighting problem was gone after deleting .idea folder and clean build.

**Comment by coder82** [comment]
Now it's not red anymore, I can't recall the version of IJ i had then, the version I have now is the latest:

IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by coder82** [comment]
This problem is back:

IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

serializer() function shows unresolved...

**Comment by natanfudge** [comment]
Problem still exists with IDEA 2019.2 and Kotlin plugin 1.3.50-eap-5.

**Comment by sandwwraith** [comment]
Have you tried to reimport the project?

**Comment by natanfudge** [comment]
Yes, it fixes it, but i have to do it every time i start the IDE...

**Comment by coder82** [comment]
To me it doesn’t fix it by restarting, I also have to delete the gradle.xml from .idea dir to fix it.
Really annoying because restarting means quite a lot of reload, reindex, reimport etc...

**Comment by andylamax** [comment]
None of the above options worked for me. 

Using
IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-30-generic

gradle would compile well. But IDEA would highlight `ClassName.serializer()` (the serializer method) and state that it is an "unresolved reference"

**Comment by Gennady77** [comment]
I have the same problem in Android Studio.

**Comment by coder82** [comment]
> @fracturizer @coder82 Can you please write versions of your IDEs?

It's long I don't see this anymore, it was happening with the version I wrote above.

**Comment by smaudet** [comment]
...Pretty sure this is back. Why is gradle so horrible/indecipherable to use...

IntelliJ 2019.2.2 does not see the serialization stuff. Only the 1.2 stuff seemed to work.

Such BS.

**Comment by chrisjenx** [comment]
This was fixed a long time ago for me, couple of things if you haven't checked already, make sure gradle is up to date, make sure the serilization dep is up to date, make sure kotlin is up to date (as it's bundled into the compiler plugin). Make sure you have cleaned and then invalidated caches. 
IF after all of that it still doesn't work, please create a minimum reproduceable example and create a ticket so they can fix it.

**Comment by denmusic1992** [comment]
Yes, I faced the same issue when developing multiplatform applications.
I resolved it by adding to _build.gradle_:
```gradle
plugins {
    ...
    id 'org.jetbrains.kotlin.multiplatform'
    id 'kotlinx-serialization'
}
```
and also
```gradle
buildscript {
    ...
    dependencies {
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVer"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlinVer"
    }
}
```
where _kotlin_version = 1.3.61_

**Comment by haohcraft** [comment]
I ran into the same issue on `kotlin_version=1.3.60` and resolved it by rebuild the project after switching to `kotlin_version=1.3.50`. The bug is constantly reproducible and resolvable to me.

**Comment by mdeverdelhan** [comment]
Just reproduced using IntelliJ IDEA / Maven:

- Error: **_Error:(83, 53) Kotlin: Unresolved reference: serializer_**
- IDE: **_IntelliJ IDEA 2018.2.2 (Community Edition)_**
- pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tld.group</groupId>
    <artifactId>artifact</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <name>artifact</name>
    <description>description</description>

    <properties>
        <kotlin.version>1.3.61</kotlin.version>
        <serialization.version>0.14.0</serialization.version>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
        <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
        <main.class>MainClass</main.class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-runtime</artifactId>
            <version>${serialization.version}</version>
        </dependency>
    </dependencies>

    <build>

        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <configuration>
                    <experimentalCoroutines>enable</experimentalCoroutines>
                    <plugin>kotlinx-serialization</plugin>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-serialization</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>${main.class}</mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>
```

**Comment by qlereboursBS** [comment]
I still have this issue in a multi-modules project with maven.
If the configuration is in each module's pom it works, but if it's in the parent pom, it won't work.
Anyone has this issue?

**Comment by sandwwraith** [comment]
@qlereboursBS Plugin should be applied to each module in your project, where you want to use `@Serializable` annotation
